# Define global constants

CONFIG_USE_HTTPS = 'CONFIG.USE.HTTPS'

APP_KEY_SLC = 'SHORT_LIVED_CACHE'
APP_KEY_AUTHENTICATE = 'AUTHENTICATE'
APP_KEY_PLUGINS = 'PLUGINS'
APP_KEY_PROCESSORS = 'PROCESSORS'

PROPERTY_DEFINITIONS = 'PROPERTY_DEFINITIONS'

PROPERTY_SERVER_PORT_KEY = 'SERVER.PORT'
PROPERTY_SERVER_SECRET_KEY = 'SERVER.SECRET.KEY'
PROPERTY_SERVER_HOST_KEY = 'SERVER.HOST'
PROPERTY_SERVER_AUTH_TIMEOUT_KEY = 'SERVER.AUTH.TIMEOUT'

PROPERTY_SERVER_MEDIA_PRIMARY_FOLDER = 'SERVER.MEDIA.PRIMARY.FOLDER'
PROPERTY_SERVER_MEDIA_ARCHIVE_FOLDER = 'SERVER.MEDIA.ARCHIVE.FOLDER'
PROPERTY_SERVER_MEDIA_TEMP_FOLDER = 'SERVER.MEDIA.TEMP.FOLDER'
PROPERTY_SERVER_MEDIA_READY = 'SERVER.MEDIA.READY'

PROPERTY_SERVER_VOLUME_FOLDER = 'SERVER.VOLUME.FOLDER'
PROPERTY_SERVER_VOLUME_FORMAT = 'SERVER.VOLUME.FORMAT'
PROPERTY_SERVER_VOLUME_READY = 'SERVER.VOLUME.READY'

COMMON_MEDIA_RATINGS = [0, 40, 60, 80, 90, 100, 200]

MAX_WORKERS = 7