import os
import hashlib


def generate_unique_string(file_path):
    """
    Generate a unique string for a given file path.

    The unique string is generated by hashing the folder path and the file name.
    The hash is a SHA256 hash.

    Args:
        file_path (str): The path to the file.

    Returns:
        str: The unique string.
    """
    # Get the directory name from the file path and hash it using SHA256
    folder_hash = hashlib.sha256(os.path.dirname(file_path).encode()).hexdigest()

    # Get the base name (file name) from the file path and hash it using SHA256
    file_hash = hashlib.sha256(os.path.basename(file_path).encode()).hexdigest()

    # Combine the folder hash and file hash to create a unique string
    unique_string = f"{folder_hash}_{file_hash}"

    # Return the unique string
    return str(unique_string)