name: Publish docker image

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Frontend
        uses: actions/checkout@v4
        with:
          repository: mgatelabs/LimitedMediaServerSite
          path: LimitedMediaServerSite

      - name: Checkout Backend
        uses: actions/checkout@v4
        with:
          path: LimitedMediaServer
          
      - name: dockerignore
        run: |
          cp LimitedMediaServer/.dockerignore ./

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: |
            linux/amd64
            linux/arm64
          context: .
          file: ./LimitedMediaServer/Dockerfile
          pull: true
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/limitedmediaserver:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/limitedmediaserver:${{ github.ref_name }}